# Entry point port
server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      # Remove problematic default filters for WebSocket compatibility
      # default-filters:
      #   - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      routes:
        - id: user_service_route
          uri: http://user-service:8083
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2

        - id: project_service_route
          uri: http://project-service:8082
          predicates:
            - Path=/api/projects/**
          filters:
            - StripPrefix=1

        - id: task_service_route
          uri: http://task-service:8081
          predicates:
            - Path=/api/tasks/**

        - id: comment_service_route
          uri: http://comment-service:8088
          predicates:
            - Path=/api/comments/**
          filters:
            - StripPrefix=1

        - id: notification_service_route
          uri: http://notification-service:8086
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1

        - id: websocket_service_route
          uri: ws://websocket-service:8085
          predicates:
            - Path=/ws/updates/**
          metadata:
            connect-timeout: 5000
            response-timeout: 5000

        - id: auth_service_route
          uri: http://user-service:8083
          predicates:
            - Path=/api/auth/**
          filters:
            # We need to strip 1 prefix part: "/api"
            # Request /api/auth/login -> becomes /auth/login for the user-service
            - StripPrefix=1

# JWT disabled by default for easier development
jwt:
  enabled: false
  secret: my-very-secret-key-for-jwt-signing

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.pm.apigateway: DEBUG
    reactor.kafka.sender: INFO # Added for Kafka sender logging
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [CorrID: %X{correlationId:-N/A}] - %msg%n" # Added logging pattern

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  config:
    activate:
      on-profile: docker
---
spring:
  config:
    activate:
      on-profile: dev
