server:
  port: 8083
  servlet:
    context-path: /api/users

services:
  user-service:
    url: http://user-service:8083
  task-service:
    url: http://task-service:8081
  project-service:
    url: http://project-service:8082
  comment-service:
    url: http://comment-service:8088

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/userdb
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: " com.pm.commoncontracts.*"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: user-service-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: " com.pm.commoncontracts.*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    refresh:
      enabled: true

# Production mode - JWT enabled
jwt:
  enabled: true
  secret: ${JWT_SECRET:my-very-secret-key-for-jwt-signing}

# Production security configuration
security:
  require-ssl: true
