server:
  port: 8083
  servlet:
    context-path: /api/users

services:
  user-service:
    url: http://user-service:8083
  task-service:
    url: http://task-service:8081
  project-service:
    url: http://project-service:8082
  comment-service:
    url: http://comment-service:8088

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/userdb
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: " com.pm.commoncontracts.*"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: user-service-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: " com.pm.commoncontracts.*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    refresh:
      enabled: true

# JWT disabled by default for easier development
jwt:
  enabled: false
  secret: my-very-secret-key-for-jwt-signing

kafka:
  topic:
    user-events: user-events

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.pm.userservice: DEBUG
    reactor.kafka.sender: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [CorrID: %X{correlationId:-N/A}] - %msg%n"

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://mongo:27017/userdb
  kafka:
    bootstrap-servers: kafka:9092
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/userdb
  kafka:
    bootstrap-servers: localhost:9092
